public  class practice { 
    public void printPractice() {
    Integer myFavNum=3344;
    Boolean isYourClassRight=false;
    Long myFavLongNum=982574958L;

    System.debug('This is my Practice page');
    System.debug(myFavNum + ' is my favorite number');
    System.debug(myFavLongNum +' is my favorite long number');
    System.debug('Are you in 11th grade? Answer: ' +isYourClassRight);

     

    }
}
